save_dir: "data/"

root_dir: "Final_Dataset"

save_prefix: "processed_data"

training:
  num_epochs: 20
  batch_size: 90
  num_workers: 2
  lr: 0.001
  weight_decay: 0.0001
  resume: True


model:
  model_dir: "models"
  gray_latest: "gray_latest_model.pth"
  gray_best: "gray_best_model.pth"
  clahe_latest: "clahe_latest_model.pth"  
  clahe_best: "clahe_best_model.pth"
  edges_latest: "edges_latest_model.pth"
  edges_best: "edges_best_model.pth"
  rgb_latest: "rgb_latest_model.pth"
  rgb_best: "rgb_best_model.pth"


graph:
  graph_dir: "Graphs"
  gray_plot: "gray_train_curves.png"
  clahe_plot: "clahe_train_curves.png"
  edges_plot: "edges_train_curves.png"
  rgb_plot: "rgb_train_curves.png"
